server.port=8086
spring.kafka.consumer.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=amount-deposit-event
spring.kafka.consumer.properties.spring.json.trusted.packages=ua.mai.zine.kafka.*

spring.kafka.consumer.izolation.level=READ_COMMITTED