logging:
    level:
        ROOT: INFO
server:
    port: 8088
#    servlet:
#        session:
#            cookie:
#                http-only: true
#    forward-headers-strategy: FRAMEWORK
#    tomcat:
#        additional-tld-skip-patterns: "*"
spring:
    mvc:
        problemdetails:
            enabled: true
    main.banner-mode: off
    main:
        allow-bean-definition-overriding: true
    lifecycle.timeout-per-shutdown-phase: 9s
    application:
        name: zine Kafka Spring Boot Application
    messages:
        basename: i18n/messages
    shutdown: graceful

    kafka:
        bootstrap-servers: localhost:9092
        listener:
            # Как подтверждается обработка сообщения consumer-а (KafkaListenerContainerFactory):
            ack-mode: manual
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            # Сколько подтверждений нужно от брокеров перед тем, как считать сообщение отправленным:
            acks: 1
            retries: 3
#        consumer:
#            group-id: inbound-transaction-processing
#            auto-offset-reset: earliest
#            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#            enable-auto-commit: false
#            properties:
#                "[spring.json.value.default.type]": "io.maksymdobrynin.async.kafka.api.ChargeRequest"
#                partition.assignment.strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor

management:
    endpoints:
        web:
            exposure:
                include: "*"

