<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.10</version>
<!--        <version>3.4.5</version>-->
<!--        <version>3.4.2</version>-->
<!--        <version>4.0.2</version>-->
        <relativePath /> <!-- lookup parent from repository -->
    </parent>

    <groupId>ua.mai.zine.jpa</groupId>
    <artifactId>zine-jpa</artifactId>
    <version>0.0.0.001-SNAPSHOT</version>
    <name>JPA :: [pom]</name>
    <description>zine project for learning JPA</description>
    <packaging>pom</packaging>

    <inceptionYear>2025</inceptionYear>
    <repositories>
    </repositories>

    <modules>
        <module>applications</module>
        <module>modules</module>
    </modules>

    <properties>
        <mysql.version>8.0.21</mysql.version>
        <springdoc.version>2.8.8</springdoc.version>
        <spring-boot-configuration-processor.version>3.2.1</spring-boot-configuration-processor.version>
        <maven-compiler-plugin>3.13.0</maven-compiler-plugin>
        <mapstruct.version>1.5.5.Final</mapstruct.version>
    </properties>

    <dependencyManagement>
        <dependencies>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin}</version> <!-- Use a recent version -->
                <configuration>
                    <source>25</source>
                    <target>25</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
<!--                            <version>1.18.42</version> &lt;!&ndash; Match the dependency version &ndash;&gt;-->
                        </path>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${mapstruct.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

<!--            <plugin>-->
<!--                <groupId>org.projectlombok</groupId>-->
<!--                <artifactId>lombok-maven-plugin</artifactId>-->
<!--                <version>1.18.42</version>-->
<!--                <executions>-->
<!--                    <execution>-->
<!--                        <phase>generate-sources</phase>-->
<!--                        <goals>-->
<!--                            <goal>delombok</goal>-->
<!--                        </goals>-->
<!--                    </execution>-->
<!--                </executions>-->
<!--            </plugin>-->
        </plugins>
    </build>

</project>
