logging:
    level:
        ROOT: INFO

#        org.springframework.kafka: DEBUG
#        org.springframework.kafka.core.KafkaTemplate: DEBUG
#        org.apache.kafka: DEBUG
#        org.apache.kafka.clients.producer: DEBUG

server:
    port: 8089
#    servlet:
#        session:
#            cookie:
#                http-only: true
#    forward-headers-strategy: FRAMEWORK
#    tomcat:
#        additional-tld-skip-patterns: "*"
spring:
    mvc:
        problemdetails:
            enabled: true
    main.banner-mode: off
    main:
        allow-bean-definition-overriding: true
    lifecycle.timeout-per-shutdown-phase: 9s
    application:
        name: zine Kafka Consumer Application
    messages:
        basename: i18n/messages
    shutdown: graceful

    kafka:
        bootstrap-servers: localhost:9092
        listener:
            # Как подтверждается обработка сообщения consumer-а (KafkaListenerContainerFactory):
            ack-mode: manual
        consumer:
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            group-id: product-create-group
#            auto-offset-reset: earliest
#            enable-auto-commit: false
            properties.spring.json.trusted.packages: ua.mai.zine.kafka.event # "*"
#                "[spring.json.value.default.type]": "io.maksymdobrynin.async.kafka.api.ChargeRequest"
#                partition.assignment.strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor

    datasource:
        url: jdbc:postgresql://localhost:5432/zine-kafka
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
#   type: com.zaxxer.hikari.HikariDataSource          # обычно не нужно, уже по умолчанию
        hikari:
            pool-name: Zine-JPA-Hikari       # Имя пула (удобно в логах и мониторинге)
            # Основные настройки пула (самое важное)
            maximum-pool-size: 10            # Начните с 10–20, подстраивайте под нагрузку и CPU (часто (ядра × 2) + 5–10)
            minimum-idle: 5                  # Минимум простаивающих соединений (часто = 40–60% от maximum-pool-size)
            idle-timeout: 300000             # 5 минут — когда соединение вернётся в пул, если не нужно
            max-lifetime: 1800000            # 30 минут — максимальное время жизни соединения (MySQL часто убивает >8–24 ч)
            connection-timeout: 30000        # 30 секунд — максимальное ожидание соединения из пула
            leak-detection-threshold: 60000  # 60 секунд — логирует утечки соединений (очень полезно в проде)
    jpa:
        hibernate:
#            ddl-auto: none        # отключен
#            ddl-auto: validate    # только проверка
            ddl-auto: update      # создаёт недостающие таблицы
#            ddl-auto: create      # пересоздаёт схему
#            ddl-auto: create-drop # удаляет при shutdown
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc.time_zone: Europe/Kyiv
                format_sql: true

zine:
    kafka:
        product-create-topic:
            name: product-create-topic
#            partitions: 3
        shop-create-topic:
            name: shop-create-topic
#            partitions: 3

management:
    endpoints:
        web:
            exposure:
                include: "*"

