<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ua.mai.zine.kafka-transaction</groupId>
    <artifactId>kafka-transaction</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>kafka-transaction :: kafka-transaction</name>
    <description>modules in </description>

	<modules>
        <module>core</module>
        <module>transfer-service</module>
        <module>deposit-service</module>
        <module>withdrawal-service</module>
        <module>mock-service</module>
    </modules>

</project>