### 1
POST http://localhost:8088/products
Content-Type: application/json

{ "title": "Apple6", "price": 15.5, "quantity": 11 }


### 2
POST 127.0.0.1:8088/shops
Content-Type: application/json

{ "shop": "mag", "address": "New York" }

