
### 1
POST http://localhost:8088/products
Content-Type: application/json

{ "title": "Apple6", "price": 15.5, "quantity": 11 }


### 2 Вызывает RetryableException, которое приводит к retray message
POST http://localhost:8088/products
Content-Type: application/json

{ "title": "RetryableException", "price": 15.5, "quantity": 11 }


### 3 Вызывает NonRetryableException, которое сразу приводит к размещению message в DLQ
POST http://localhost:8088/products
Content-Type: application/json

{ "title": "NonRetryableException", "price": 15.5, "quantity": 11 }


### 4
POST 127.0.0.1:8088/products
Content-Type: application/json

{ "shop": "mag", "address": "New York" }

