# Docker stack name
name: zine-redis-learning

services:

  app-read-through:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zine-redis-app-read_through
    ports:
      - "8081:8080"
    depends_on:
      - redis
    environment:
#      - SPRING_PROFILES_ACTIVE=docker
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres?TimeZone=Europe/Kyiv
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - zine-redis-net

  redis:
    image: redis:8.6
    container_name: zine-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - zine-redis-net
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:17.9
#    image: postgres:16.13
    container_name: zine-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - zine-redis-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-insight:
    image: redis/redisinsight:latest
    container_name: zine-redis-insight
    restart: always
    depends_on:
      - redis
    ports:
      - "5540:5540"
    volumes:
      - zine-redis-insight:/data
    networks:
      - zine-redis-net
volumes:
  redis_data:
  zine-redis-insight:
  pgdata:

networks:
  zine-redis-net:
    driver: bridge

